import { createTemplate } from "bingo";

const template = createTemplate({
  produce() {
    return {
      files: {
        "README.md": `# Hello, world!

> This repository was generated by [bingo-examples/create-example-minimal](https://github.com/bingo-examples/create-example-minimal).`,
      },
    };
  },
});

export default template;

export const { createConfig } = template;
